services:
  client:
    build: './client'
    container_name: 'client'
    stdin_open: true
    tty: true

  nginx:
    image: nginx:latest
    container_name: 'nginx'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /app/Portfolio/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/letsencrypt/live/www.hash-view.com
    depends_on:
      - server
      - client
    stdin_open: true
    tty: true
